services:
  service-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect
    volumes:
      - pg-data:/bitnami/postgresql
    
volumes:
  pg-data: